### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by EattheKey** [diy/opensourcerer.diy.org#10]
I've found diy.org by chance, I think that you are doing a tremendous work for the children and also for teachers and parents. I''m sharing the page with everyones.
Even if I'm older than must of the diy's users I'm learning a lot of thing.
Thank you!
I'm an art student in Colombia that would be glad to collaborate with you!

About the open sourcerer guide I think that you could make a little more visible the differences between mac and pc. That is all, the rest I think it is very welñ done!

**Comment by thisandagain** [comment]
Awesome! I'll def. look into adding some details on the Mac/PC front. Thank you so much for the feedback! :smile:
