### ISSUE TITLE
Report an Issue on GitHub

### ISSUE THREAD

**Issue by itbsStefan** [diy/opensourcerer.diy.org#13]
So I dont know where to put all the screenshots and liked to see them from others.
Where is the upload place?
![pushinbash_2014-02-12](https://f.cloud.github.com/assets/2198480/2162654/f1f1fe7e-94d4-11e3-81be-679638a0124b.png)

**Comment by thisandagain** [comment]
It's on DIY.org, just click "Did It!" next to the challenge.
