### ISSUE TITLE
Wrong Windows command in "Push Changes in Bash"

### ISSUE THREAD

**Issue by burgzt** [diy/opensourcerer.diy.org#7]
Hello.

In Windows Git Bash don't work command "OPEN". Git Bash responds with: "open: command not found". I opened file manually, but maybe you can add some code string with example of properly Windows command? This problem occures in section "Push Changes in Bash".

Thank you and good luck!

**Comment by jlord** [comment]
Oo! Thanks! I'll double check the correct command and fix it. Thanks for the report!!
