### ISSUE TITLE
Window 8 - no My Documents directory.

### ISSUE THREAD

**Issue by ChickenHunterVT** [diy/opensourcerer.diy.org#9]
on Windows 8 the following did not work for us..
"cd My\ Documents/"

Shawn@SHAWNSLAPTOP /c/Users/Public/Workspace/diy_open_sourcerer/open-sourcerer (
master)
$ cd My\ Documents/
sh.exe": cd: My Documents/: No such file or directory

we could of used used $homepath 

Shawn@SHAWNSLAPTOP /c/Users/Public/Workspace/diy_open_sourcerer/open-sourcerer (
master)
$ cd $homepath

**Comment by thisandagain** [comment]
Thanks for the feedback! Fixed! :smile:
